name: "Armada"
version: "0.0.3"
usage: "Manages multiple Helm charts with a centralized Armada yaml"
description: |-
  This plugin provides Helm access to Armada. A tool for managing
  multiple Helm charts with dependencies by centralizing all configurations
  in a single Armada yaml and providing lifecycle hooks for all Helm releases
  usage:
    $ helm armada tiller --status
    $ helm armada apply /examples/openstack-helm.yaml
ignoreFlags: false
useTunnel: false
command: "sh $HELM_PLUGIN_DIR/controller.sh"
