#!/usr/bin/env python

import yaml
import tempfile
import sys
import os
import argparse
from supermutes.dot import dotify
from armada.armada import Armada
from armada.logutil import *

SOURCE_GIT = "git"
DESCRIPTION = "Armada"

# special top level parameters
# we will copy to all configs
COPY_LIST=['global']

def parse_args():

    ap = argparse.ArgumentParser(description=DESCRIPTION)
    ap.add_argument('--debug', action='store',
                    default=False, required=False, help='Enable debug logging')
    ap.add_argument('-c', '--config', action='store',
                    required=True, help='Path to YAML File or Directory')
    ap.add_argument('-d', '--dry-run', action='store',
                    default=False, required=False, help='Enable dry-run flag on all Tiller Calls')

    return ap.parse_args()


def run(args):

    armada = Armada(args)
    armada.sync()


if __name__ == '__main__':

    args = parse_args()
    setup_logging(args)

    try:
        run(args)
        sys.exit(0)
    except Exception as err:
        LOG.exception(err)
        sys.exit(1)


